# Bandit Python security scanner configuration
# Run with: bandit -c .bandit.yaml -r python/

skips: []
exclude_dirs:
  - .venv
  - venv
  - __pycache__
  - .git
  - tests

# High severity checks
tests:
  - B102  # exec_used
  - B103  # set_bad_file_permissions
  - B104  # hardcoded_bind_all_interfaces
  - B105  # hardcoded_password_string
  - B106  # hardcoded_password_funcarg
  - B107  # hardcoded_password_default
  - B108  # hardcoded_tmp_directory
  - B110  # try_except_pass
  - B112  # try_except_continue
  - B501  # request_with_no_cert_validation
  - B502  # ssl_with_bad_version
  - B506  # yaml_load
  - B608  # hardcoded_sql_expressions
  - B609  # linux_commands_wildcard_injection
