#!/bin/bash
# Gemini merge specs script - merges delta specs back to main specs
# Usage: ./gemini-merge-specs.sh <change-id> <strategy> <spec-file>

set -euo pipefail

CHANGE_ID="$1"
STRATEGY="$2"
SPEC_FILE="$3"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

echo "🔄 Merging specs with Gemini: $SPEC_FILE ($STRATEGY)"

# Use GEMINI.md context (generated by CLI)
export GEMINI_INSTRUCTIONS_FILE="$PROJECT_ROOT/agentd/changes/$CHANGE_ID/GEMINI.md"

DELTA_SPEC="$PROJECT_ROOT/agentd/changes/$CHANGE_ID/specs/$SPEC_FILE"
MAIN_SPEC="$PROJECT_ROOT/agentd/specs/$SPEC_FILE"

PROMPT=$(cat << EOF
# Agentd Archive: Spec Merging Task

Merge spec deltas back to main specification using **${STRATEGY}** strategy.

## Context
- Change ID: ${CHANGE_ID}
- Spec file: ${SPEC_FILE}
- Strategy: ${STRATEGY}
- Delta spec: agentd/changes/${CHANGE_ID}/specs/${SPEC_FILE}
- Main spec: agentd/specs/${SPEC_FILE}

## Your Task

Read both the delta spec and main spec (if it exists), then merge them according to the strategy:

**Full Rewrite**: Rewrite the entire spec incorporating all changes. Maintain consistent style and structure.

**Differential Merge**: Apply ONLY the specified changes. Preserve all other content exactly as-is.

**Hybrid**: Rewrite affected sections, preserve unaffected sections. Ensure smooth transitions.

## Output

Write the merged spec to: agentd/specs/${SPEC_FILE}

Ensure the output follows the spec schema with:
- Required headings: # Specification:, ## Overview, ## Requirements
- Requirement format: ### R\d+:
- Scenario format: #### Scenario:
- WHEN/THEN clauses in scenarios
EOF
)

echo "$PROMPT" | gemini agentd:merge-specs -m gemini-3-flash-preview --resume latest --output-format stream-json
